export const tableColumns = {
  tenants: [
    { field: "schoolName", headerName: "School Name" },
    { field: "contactAddress.street", headerName: "Street Address" },
    { field: "contactAddress.city", headerName: "City" },
    { field: "contactAddress.state", headerName: "State" },
    { field: "contactAddress.zip", headerName: "Zip Code" },
    { field: "contactPhone", headerName: "Contact Phone" },
    { field: "contactEmail", headerName: "Contact Email" },
    { field: "adminFullName", headerName: "Admin Full Name" },
    { field: "adminPhone", headerName: "Admin Phone" },
    { field: "adminEmail", headerName: "Admin Email" },
    { field: "subscriptionPlan", headerName: "Subscription Plan" },
    { field: "domain", headerName: "Domain" },
    { field: "logo", headerName: "Logo", type: "profilePic" },
    { field: "caption", headerName: "Caption" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" }
  ],

  classes: [
    { field: "className", headerName: "Class Name" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
    ],
  students: [
    // Personal Details
    { field: "firstName", headerName: "First Name" },
    { field: "middleName", headerName: "Middle Name" },
    { field: "lastName", headerName: "Last Name" },
    { field: "dateOfBirth", headerName: "Date of Birth" },
    { field: "gender", headerName: "Gender" },

    // Identification Details
    { field: "aadhaarNumber", headerName: "Aadhaar Number" },
    { field: "casteCategory", headerName: "Caste Category" },
    { field: "subCaste", headerName: "Sub Caste" },
    { field: "religion", headerName: "Religion" },
    { field: "motherTongue", headerName: "Mother Tongue" },
    { field: "bloodGroup", headerName: "Blood Group" },
    { field: "nationality", headerName: "Nationality" },
    { field: "identificationMarks", headerName: "Identification Marks" },

    // Admission Details
    { field: "classApplyingFor", headerName: "Class Applying For" },
    { field: "mediumOfInstruction", headerName: "Medium of Instruction" },
    { field: "previousSchoolName", headerName: "Previous School Name" },
    { field: "previousClassAttended", headerName: "Previous Class Attended" },
    { field: "transferCertificateNo", headerName: "Transfer Certificate Number" },
    { field: "dateOfIssueTC", headerName: "Date of Issue of TC" },
    { field: "modeOfTransport", headerName: "Mode of Transport" },

    // Parent/Guardian Details
    { field: "fatherName", headerName: "Father's Name" },
    { field: "fatherPhone", headerName: "Father's Phone Number" },
    { field: "fatherOccupation", headerName: "Father's Occupation" },
    { field: "fatherAadhaar", headerName: "Father's Aadhaar Number" },
    { field: "motherName", headerName: "Mother's Name" },
    { field: "motherPhone", headerName: "Mother's Phone Number" },
    { field: "motherOccupation", headerName: "Mother's Occupation" },
    { field: "motherAadhaar", headerName: "Mother's Aadhaar Number" },
    { field: "guardianName", headerName: "Guardian's Name" },
    { field: "guardianRelation", headerName: "Guardian's Relation to Student" },
    { field: "guardianContact", headerName: "Guardian's Contact Number" },

    // Address Details
    { field: "permanentAddress", headerName: "Permanent Address" },
    { field: "state", headerName: "State" },
    { field: "pincode", headerName: "Pincode" },

    // Fee & Scholarship Details
    { field: "feePaymentMode", headerName: "Fee Payment Mode" },
    { field: "bankAccountDetails", headerName: "Bank Account Details" },
    { field: "midDayMealEligibility", headerName: "Mid-Day Meal Eligibility" },

    // Grade & Section (Snapshot)

    // Documents
    { field: "studentPassportPhoto", headerName: "Student Passport Photo" },
    { field: "motherPassportPhoto", headerName: "Mother's Passport Photo" },
    { field: "fatherPassportPhoto", headerName: "Father's Passport Photo" },
    { field: "guardianPassportPhoto", headerName: "Guardian's Passport Photo" },
    { field: "studentAadharCopy", headerName: "Student Aadhaar Copy" },
    { field: "parentsAadharCopy", headerName: "Parents' Aadhaar Copy" },
    { field: "casteCertificateCopy", headerName: "Caste Certificate Copy" },
    { field: "birthCertificateCopy", headerName: "Birth Certificate Copy" },
    { field: "tcCopy", headerName: "Transfer Certificate Copy" },
    { field: "conductCertificateCopy", headerName: "Conduct Certificate Copy" },
    { field: "previousYearsMarksheetCopy", headerName: "Previous Years' Marksheet Copy" },
    { field: "incomeCertificateCopy", headerName: "Income Certificate Copy" },

    // Tenant ID

    // Metadata
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  grades: [
    { field: "course.courseName", headerName: "Course Name" },
    { field: "gradeName", headerName: "Grade Name" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  course: [
    { field: "courseName", headerName: "Course Name" },
    { field: "description", headerName: "Course Description" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  section: [
    { field: "grade.gradeName", headerName: "Grade Name" },
    { field: "sectionName", headerName: "Section Name" },
    { field: "sectionInCharge.fullName", headerName: "Section In-Charge" },
    { field: "room.roomNumber", headerName: "Room" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  academicYears: [
    { field: "name", headerName: "Academic Year" },
    { field: "startDate", headerName: "Start Date" },
    { field: "endDate", headerName: "End Date" },
    { field: "status", headerName: "Status" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  teachers: [
    { field: "fullName", headerName: "Full Name" },
    { field: "email", headerName: "Email" },
    { field: "phone", headerName: "Phone" },
    { field: "gender", headerName: "Gender" },
    { field: "employeeCode", headerName: "Employee Code" },
    { field: "profilePhotoUrl", headerName: "Profile Photo" },
    { field: "yearsOfExperience", headerName: "Years of Experience" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  teacherCapabilities: [
    { field: "teacher.fullName", headerName: "Teacher" },
    { field: "subject.subjectName", headerName: "Subject" },
    { field: "course.courseName", headerName: "Course" },
    { field: "grade.gradeName", headerName: "Grade" },
    { field: "expertiseLevel", headerName: "Expertise Level" },
    { field: "isPrimary", headerName: "Primary", type: "boolean" },
    { field: "priorityScore", headerName: "Priority" },
    { field: "canBeClassTeacher", headerName: "Can Be Class Teacher", type: "boolean" },
    { field: "remarks", headerName: "Remarks" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  sectionSubjects: [
    { field: "section.sectionName", headerName: "Section" },
    { field: "section.grade.gradeName", headerName: "Grade" },
    { field: "subject.subjectName", headerName: "Subject" },
    { field: "isElective", headerName: "Is Elective", type: "boolean" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  teacherAssignments: [
    { field: "teacher.fullName", headerName: "Teacher" },
    { field: "sectionSubject.section.sectionName", headerName: "Section" },
    { field: "sectionSubject.subject.subjectName", headerName: "Subject" },
    { field: "sectionSubject.section.grade.gradeName", headerName: "Grade" },
    { field: "academicYear.name", headerName: "Academic Year" },
    { field: "role", headerName: "Role" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  timetablePeriods: [
    { field: "name", headerName: "Period Name" },
    { field: "type", headerName: "Type" },
    { field: "structure.name", headerName: "Structure" },
    { field: "startTime", headerName: "Start Time" },
    { field: "endTime", headerName: "End Time" },
    { field: "sortOrder", headerName: "Sort Order" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  timetableEntries: [
    { field: "dayOfWeek", headerName: "Day" },
    { field: "period.name", headerName: "Period" },
    { field: "sectionSubject.section.sectionName", headerName: "Section" },
    { field: "sectionSubject.subject.subjectName", headerName: "Subject" },
    { field: "teacherAssignment.teacher.fullName", headerName: "Teacher" },
    { field: "room", headerName: "Room" },
    { field: "academicYear.name", headerName: "Academic Year" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  attendanceSessions: [
    { field: "section.sectionName", headerName: "Section" },
    { field: "date", headerName: "Date" },
    { field: "contextType", headerName: "Context Type" },
    { field: "contextName", headerName: "Context Name" },
    { field: "period.name", headerName: "Period" },
    { field: "shift", headerName: "Shift" },
    { field: "takenBy.fullName", headerName: "Taken By" },
    { field: "_count.marks", headerName: "Total Marks" },
    { field: "academicYear.name", headerName: "Academic Year" },
    { field: "notes", headerName: "Notes" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],

  // ─── Fee Management ──────────────────────────────────────────────────────
  feeHeads: [
    { field: "name", headerName: "Fee Head Name" },
    { field: "description", headerName: "Description" },
    { field: "isOptional", headerName: "Optional", type: "boolean" },
    { field: "sortOrder", headerName: "Sort Order" },
    { field: "_count.sectionFeeHeads", headerName: "Sections" },
    { field: "_count.studentFeeHeads", headerName: "Students" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  sectionFees: [
    { field: "section.sectionName", headerName: "Section" },
    { field: "section.grade.gradeName", headerName: "Grade" },
    { field: "academicYear.name", headerName: "Academic Year" },
    { field: "termCount", headerName: "Terms" },
    { field: "_count.studentFees", headerName: "Students" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  feeTerms: [
    { field: "name", headerName: "Term Name" },
    { field: "dueDate", headerName: "Due Date" },
    { field: "sortOrder", headerName: "Sort Order" },
    { field: "sectionFee.section.sectionName", headerName: "Section" },
    { field: "sectionFee.academicYear.name", headerName: "Academic Year" },
    { field: "_count.payments", headerName: "Payments" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  studentFees: [
    { field: "enrollment.student.firstName", headerName: "Student First Name" },
    { field: "enrollment.student.lastName", headerName: "Student Last Name" },
    { field: "enrollment.rollNumber", headerName: "Roll Number" },
    { field: "enrollment.section.sectionName", headerName: "Section" },
    { field: "totalActualFee", headerName: "Actual Fee" },
    { field: "totalNegotiatedFee", headerName: "Negotiated Fee" },
    { field: "discountType", headerName: "Discount Type" },
    { field: "discountValue", headerName: "Discount Value" },
    { field: "allocationMethod", headerName: "Allocation" },
    { field: "_count.payments", headerName: "Payments" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  feePayments: [
    { field: "studentFee.enrollment.student.firstName", headerName: "Student" },
    { field: "studentFee.enrollment.rollNumber", headerName: "Roll Number" },
    { field: "term.name", headerName: "Term" },
    { field: "feeHead.name", headerName: "Fee Head" },
    { field: "amountPaid", headerName: "Amount Paid" },
    { field: "paymentMethod", headerName: "Payment Method" },
    { field: "transactionId", headerName: "Transaction ID" },
    { field: "status", headerName: "Status" },
    { field: "paymentDate", headerName: "Payment Date" },
    { field: "collectedBy.fullName", headerName: "Collected By" },
    { field: "remarks", headerName: "Remarks" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  feeRefunds: [
    { field: "payment.studentFee.enrollment.student.firstName", headerName: "Student" },
    { field: "payment.amountPaid", headerName: "Original Amount" },
    { field: "amount", headerName: "Refund Amount" },
    { field: "reason", headerName: "Reason" },
    { field: "refundDate", headerName: "Refund Date" },
    { field: "processedBy.fullName", headerName: "Processed By" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],

  // ─── Store Module ──────────────────────────────────────────────────────────
  storeCategories: [
    { field: "name", headerName: "Category Name" },
    { field: "description", headerName: "Description" },
    { field: "sortOrder", headerName: "Sort Order" },
    { field: "isActive", headerName: "Active", type: "boolean" },
    { field: "_count.products", headerName: "Products" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  storeProducts: [
    { field: "name", headerName: "Product Name" },
    { field: "category.name", headerName: "Category" },
    { field: "description", headerName: "Description" },
    { field: "basePrice", headerName: "Base Price" },
    { field: "isGeneral", headerName: "General", type: "boolean" },
    { field: "stockQuantity", headerName: "Stock" },
    { field: "isActive", headerName: "Active", type: "boolean" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  storeKits: [
    { field: "name", headerName: "Kit Name" },
    { field: "description", headerName: "Description" },
    { field: "totalQuantity", headerName: "Total Quantity" },
    { field: "totalPrice", headerName: "Total Price" },
    { field: "isActive", headerName: "Active", type: "boolean" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  storeOrders: [
    { field: "enrollment.student.firstName", headerName: "Student" },
    { field: "enrollment.rollNumber", headerName: "Roll Number" },
    { field: "enrollment.section.sectionName", headerName: "Section" },
    { field: "orderDate", headerName: "Order Date" },
    { field: "totalAmount", headerName: "Total Amount" },
    { field: "status", headerName: "Status" },
    { field: "remarks", headerName: "Remarks" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  storePendingItems: [
    { field: "orderItem.order.enrollment.student.firstName", headerName: "Student" },
    { field: "productName", headerName: "Product" },
    { field: "quantity", headerName: "Quantity" },
    { field: "status", headerName: "Status" },
    { field: "collectedAt", headerName: "Collected At" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],

  // ─── Exam Module ────────────────────────────────────────────────────────────
  exams: [
    { field: "name", headerName: "Exam Name" },
    { field: "examType", headerName: "Exam Type" },
    { field: "academicYear.name", headerName: "Academic Year" },
    { field: "startDate", headerName: "Start Date" },
    { field: "endDate", headerName: "End Date" },
    { field: "status", headerName: "Status" },
    { field: "source", headerName: "Source" },
    { field: "_count.schedules", headerName: "Schedules" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  examSchedules: [
    { field: "exam.name", headerName: "Exam" },
    { field: "section.sectionName", headerName: "Section" },
    { field: "section.grade.gradeName", headerName: "Grade" },
    { field: "name", headerName: "Schedule Name" },
    { field: "startDate", headerName: "Start Date" },
    { field: "endDate", headerName: "End Date" },
    { field: "status", headerName: "Status" },
    { field: "_count.papers", headerName: "Papers" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  examSchedulePapers: [
    { field: "sectionSubject.subject.subjectName", headerName: "Subject" },
    { field: "examDate", headerName: "Exam Date" },
    { field: "startTime", headerName: "Start Time" },
    { field: "endTime", headerName: "End Time" },
    { field: "durationMinutes", headerName: "Duration (min)" },
    { field: "room", headerName: "Room" },
    { field: "inCharge.fullName", headerName: "In-Charge" },
    { field: "maxMarks", headerName: "Max Marks" },
    { field: "passMarks", headerName: "Pass Marks" },
    { field: "_count.marks", headerName: "Marks Entered" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
  examMarks: [
    { field: "enrollment.student.firstName", headerName: "Student First Name" },
    { field: "enrollment.student.lastName", headerName: "Student Last Name" },
    { field: "enrollment.rollNumber", headerName: "Roll Number" },
    { field: "marksObtained", headerName: "Marks Obtained" },
    { field: "isAbsent", headerName: "Absent", type: "boolean" },
    { field: "gradeLabel", headerName: "Grade" },
    { field: "remarks", headerName: "Remarks" },
    { field: "createdAt", headerName: "Created At" },
    { field: "updatedAt", headerName: "Updated At" },
  ],
};
